services:
  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    environment:
      - AUTH_SERVICE_URL=http://auth:8001
      - PRODUCT_SERVICE_URL=http://product:8002
      - CART_SERVICE_URL=http://cart:8003
    depends_on:
      - auth
      - product
      - cart

  auth:
    build: ./auth
    depends_on:
      - auth_db
    environment:
      - JWT_SECRET=secret
      - DB_HOST=auth_db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=auth_db
      - DB_PORT=5432

  product:
    build: ./products
    depends_on:
      - product_db
    environment:
      - DB_HOST=product_db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=product_db
      - DB_PORT=5432

  cart:
    build: ./cart
    depends_on:
      - cart_db
      - auth
    environment:
      - AUTH_SERVICE_URL=http://auth:8001
      - DB_HOST=cart_db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=cart_db
      - DB_PORT=5432

  auth_db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=auth_db
    ports:
      - "5433:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data

  product_db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=product_db
    ports:
      - "5434:5432"
    volumes:
      - product_data:/var/lib/postgresql/data

  cart_db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cart_db
    ports:
      - "5435:5432"
    volumes:
      - cart_data:/var/lib/postgresql/data

volumes:
  auth_data:
  product_data:
  cart_data:
