insert into products (id, name, price) values (1, 'Goldschalger', 46.99);
insert into products (id, name, price) values (2, 'Cheese - Pont Couvert', 49.52);
insert into products (id, name, price) values (3, 'Broccoli - Fresh', 13.64);
insert into products (id, name, price) values (4, 'Sprouts - Onion', 12.54);
insert into products (id, name, price) values (5, 'Fruit Salad Deluxe', 32.43);
insert into products (id, name, price) values (6, 'Crush - Grape, 355 Ml', 70.92);
insert into products (id, name, price) values (7, 'Pastry - Baked Scones - Mini', 32.48);
insert into products (id, name, price) values (8, 'True - Vue Containers', 32.78);
insert into products (id, name, price) values (9, 'Beer - Rickards Red', 31.71);
insert into products (id, name, price) values (10, 'Island Oasis - Mango Daiquiri', 58.7);
insert into products (id, name, price) values (11, 'Pancetta', 89.71);
insert into products (id, name, price) values (12, 'Longos - Grilled Salmon With Bbq', 38.67);
insert into products (id, name, price) values (13, 'Parsley - Fresh', 57.46);
insert into products (id, name, price) values (14, 'Hog / Sausage Casing - Pork', 85.04);
insert into products (id, name, price) values (15, 'Island Oasis - Magarita Mix', 83.77);
insert into products (id, name, price) values (16, 'Tofu - Soft', 65.07);
insert into products (id, name, price) values (17, 'Pail - 4l White, With Handle', 87.01);
insert into products (id, name, price) values (18, 'Wine - Pinot Noir Pond Haddock', 72.99);
insert into products (id, name, price) values (19, 'Soup - Campbells - Tomato', 86.87);
insert into products (id, name, price) values (20, 'Wine - Vouvray Cuvee Domaine', 5.58);
insert into products (id, name, price) values (21, 'Steampan - Half Size Shallow', 36.27);
insert into products (id, name, price) values (22, 'Bacardi Limon', 71.07);
insert into products (id, name, price) values (23, 'Turkey - Ground. Lean', 1.58);
insert into products (id, name, price) values (24, 'Sauce - Caesar Dressing', 15.75);
insert into products (id, name, price) values (25, 'Lid - 16 Oz And 32 Oz', 40.19);
insert into products (id, name, price) values (26, 'Wine - Mas Chicet Rose, Vintage', 92.31);
insert into products (id, name, price) values (27, 'Kirsch - Schloss', 87.75);
insert into products (id, name, price) values (28, 'Star Fruit', 75.05);
insert into products (id, name, price) values (29, 'Fennel - Seeds', 89.28);
insert into products (id, name, price) values (30, 'Gloves - Goldtouch Disposable', 5.96);
insert into products (id, name, price) values (31, 'Sugar - Crumb', 77.26);
insert into products (id, name, price) values (32, 'Jam - Apricot', 45.91);
insert into products (id, name, price) values (33, 'Creme De Cacao White', 40.21);
insert into products (id, name, price) values (34, 'Bread - Flat Bread', 45.49);
insert into products (id, name, price) values (35, 'Venison - Striploin', 58.02);
insert into products (id, name, price) values (36, 'Gingerale - Schweppes, 355 Ml', 62.38);
insert into products (id, name, price) values (37, 'Beer - Heinekin', 60.79);
insert into products (id, name, price) values (38, 'Flour Pastry Super Fine', 43.79);
insert into products (id, name, price) values (39, 'Pork - Inside', 41.44);
insert into products (id, name, price) values (40, 'Water - Spring Water, 355 Ml', 7.54);
insert into products (id, name, price) values (41, 'Tea - Decaf 1 Cup', 83.32);
insert into products (id, name, price) values (42, 'Wine - Rubyport', 17.75);
insert into products (id, name, price) values (43, 'Bread - Wheat Baguette', 37.65);
insert into products (id, name, price) values (44, 'Banana - Green', 26.39);
insert into products (id, name, price) values (45, 'Ice Cream - Vanilla', 63.73);
insert into products (id, name, price) values (46, 'Oil - Food, Lacquer Spray', 30.06);
insert into products (id, name, price) values (47, 'Bread - Triangle White', 6.42);
insert into products (id, name, price) values (48, 'Veal - Ground', 94.89);
insert into products (id, name, price) values (49, 'Pasta - Rotini, Colour, Dry', 25.24);
insert into products (id, name, price) values (50, 'Shrimp - 150 - 250', 52.04);
insert into products (id, name, price) values (51, 'Pepsi - 600ml', 92.8);
insert into products (id, name, price) values (52, 'Mushroom - Chanterelle Frozen', 61.74);
insert into products (id, name, price) values (53, 'Tart Shells - Savory, 2', 15.76);
insert into products (id, name, price) values (54, 'Muffin - Zero Transfat', 39.67);
insert into products (id, name, price) values (55, 'Sunflower Seed Raw', 57.23);
insert into products (id, name, price) values (56, 'Soupcontfoam16oz 116con', 47.79);
insert into products (id, name, price) values (57, 'Spice - Montreal Steak Spice', 31.4);
insert into products (id, name, price) values (58, 'Coffee - Hazelnut Cream', 67.97);
insert into products (id, name, price) values (59, 'Jello - Assorted', 29.17);
insert into products (id, name, price) values (60, 'Beef - Flank Steak', 76.61);
insert into products (id, name, price) values (61, 'Country Roll', 97.88);
insert into products (id, name, price) values (62, 'Zucchini - Green', 95.54);
insert into products (id, name, price) values (63, 'Garbage Bags - Black', 65.19);
insert into products (id, name, price) values (64, 'Juice - Ocean Spray Cranberry', 14.55);
insert into products (id, name, price) values (65, 'Cleaner - Pine Sol', 58.04);
insert into products (id, name, price) values (66, 'Onion - Dried', 99.39);
insert into products (id, name, price) values (67, 'Muffin - Mix - Bran And Maple 15l', 1.22);
insert into products (id, name, price) values (68, 'C - Plus, Orange', 78.19);
insert into products (id, name, price) values (69, 'Lemon Tarts', 19.58);
insert into products (id, name, price) values (70, 'Chocolate - Milk', 45.79);
insert into products (id, name, price) values (71, 'Dr. Pepper - 355ml', 75.99);
insert into products (id, name, price) values (72, 'Wine - Kwv Chenin Blanc South', 41.5);
insert into products (id, name, price) values (73, 'Rice - Sushi', 44.38);
insert into products (id, name, price) values (74, 'Sauce - Vodka Blush', 76.49);
insert into products (id, name, price) values (75, 'Kellogs All Bran Bars', 52.77);
insert into products (id, name, price) values (76, 'Versatainer Nc - 888', 1.55);
insert into products (id, name, price) values (77, 'Wine - German Riesling', 41.1);
insert into products (id, name, price) values (78, 'Pail For Lid 1537', 24.21);
insert into products (id, name, price) values (79, 'Beans - Butter Lrg Lima', 15.08);
insert into products (id, name, price) values (80, 'Sole - Iqf', 28.84);
insert into products (id, name, price) values (81, 'Wine - Toasted Head', 4.02);
insert into products (id, name, price) values (82, 'Sugar - Cubes', 82.03);
insert into products (id, name, price) values (83, 'Fiddlehead - Frozen', 12.67);
insert into products (id, name, price) values (84, 'Wine - Fontanafredda Barolo', 87.61);
insert into products (id, name, price) values (85, 'Bread - Bistro White', 80.49);
insert into products (id, name, price) values (86, 'Beef - Short Ribs', 53.67);
insert into products (id, name, price) values (87, 'Potatoes - Peeled', 60.34);
insert into products (id, name, price) values (88, 'Assorted Desserts', 24.64);
insert into products (id, name, price) values (89, 'Ham - Procutinni', 37.71);
insert into products (id, name, price) values (90, 'Rice - Jasmine Sented', 42.62);
insert into products (id, name, price) values (91, 'Muffin Puck Ww Carrot', 92.86);
insert into products (id, name, price) values (92, 'Juice - Ocean Spray Cranberry', 69.57);
insert into products (id, name, price) values (93, 'Pastry - Banana Muffin - Mini', 58.7);
insert into products (id, name, price) values (94, 'Sauce - Mint', 75.35);
insert into products (id, name, price) values (95, 'Yeast Dry - Fleischman', 97.24);
insert into products (id, name, price) values (96, 'Pork - Ham, Virginia', 70.97);
insert into products (id, name, price) values (97, 'Pastry - Butterscotch Baked', 71.61);
insert into products (id, name, price) values (98, 'Cheese - Havarti, Salsa', 59.77);
insert into products (id, name, price) values (99, 'Oven Mitts 17 Inch', 45.29);
insert into products (id, name, price) values (100, 'Flour Dark Rye', 39.7);
insert into products (id, name, price) values (101, 'Peas - Pigeon, Dry', 93.93);
insert into products (id, name, price) values (102, 'Trout - Hot Smkd, Dbl Fillet', 30.33);
insert into products (id, name, price) values (103, 'Island Oasis - Magarita Mix', 31.52);
insert into products (id, name, price) values (104, 'Quinoa', 84.68);
insert into products (id, name, price) values (105, 'Onions - Spanish', 39.92);
insert into products (id, name, price) values (106, 'Puree - Pear', 76.08);
insert into products (id, name, price) values (107, 'Coconut - Whole', 16.4);
insert into products (id, name, price) values (108, 'Juice - Happy Planet', 1.62);
insert into products (id, name, price) values (109, 'Nori Sea Weed - Gold Label', 95.66);
insert into products (id, name, price) values (110, 'Cheese - Brie, Cups 125g', 5.24);
insert into products (id, name, price) values (111, 'Plaintain', 90.06);
insert into products (id, name, price) values (112, 'Liqueur Banana, Ramazzotti', 53.85);
insert into products (id, name, price) values (113, 'Cardamon Ground', 8.56);
insert into products (id, name, price) values (114, 'Milk - 2% 250 Ml', 37.72);
insert into products (id, name, price) values (115, 'V8 Splash Strawberry Banana', 23.79);
insert into products (id, name, price) values (116, 'Nestea - Ice Tea, Diet', 58.85);
insert into products (id, name, price) values (117, 'Chocolate - White', 98.5);
insert into products (id, name, price) values (118, 'Rum - Cream, Amarula', 14.05);
insert into products (id, name, price) values (119, 'Curry Powder', 74.73);
insert into products (id, name, price) values (120, 'Myers Planters Punch', 99.14);
insert into products (id, name, price) values (121, 'Mace', 77.81);
insert into products (id, name, price) values (122, 'Vinegar - White Wine', 63.31);
insert into products (id, name, price) values (123, 'Lamb - Loin Chops', 60.34);
insert into products (id, name, price) values (124, 'Orange Roughy 4/6 Oz', 21.79);
insert into products (id, name, price) values (125, 'Wine - Merlot Vina Carmen', 21.03);
insert into products (id, name, price) values (126, 'Truffle - Whole Black Peeled', 78.95);
insert into products (id, name, price) values (127, 'Coffee - Almond Amaretto', 61.1);
insert into products (id, name, price) values (128, 'Table Cloth 54x54 Colour', 11.09);
insert into products (id, name, price) values (129, 'Bagelers - Cinn / Brown Sugar', 83.63);
insert into products (id, name, price) values (130, 'Bread - Crumbs, Bulk', 1.86);
insert into products (id, name, price) values (131, 'Quail Eggs - Canned', 46.24);
insert into products (id, name, price) values (132, 'Shrimp - 21/25, Peel And Deviened', 90.12);
insert into products (id, name, price) values (133, 'Cup - 4oz Translucent', 5.39);
insert into products (id, name, price) values (134, 'Wine - Barossa Valley Estate', 21.91);
insert into products (id, name, price) values (135, 'Wine - Marlbourough Sauv Blanc', 65.56);
insert into products (id, name, price) values (136, 'Veal - Kidney', 17.18);
insert into products (id, name, price) values (137, 'Mushroom - Porcini Frozen', 33.3);
insert into products (id, name, price) values (138, 'Kale - Red', 12.12);
insert into products (id, name, price) values (139, 'Fish - Bones', 38.88);
insert into products (id, name, price) values (140, 'Oil - Cooking Spray', 35.32);
insert into products (id, name, price) values (141, 'Propel Sport Drink', 74.68);
insert into products (id, name, price) values (142, 'Vaccum Bag - 14x20', 24.78);
insert into products (id, name, price) values (143, 'Nantucket Pine Orangebanana', 15.56);
insert into products (id, name, price) values (144, 'Veal - Provimi Inside', 99.39);
insert into products (id, name, price) values (145, 'Milk - Condensed', 11.99);
insert into products (id, name, price) values (146, 'Tea - Decaf Lipton', 71.37);
insert into products (id, name, price) values (147, 'Pepper Squash', 69.95);
insert into products (id, name, price) values (148, 'Flax Seed', 84.82);
insert into products (id, name, price) values (149, 'Sauce - Marinara', 88.54);
insert into products (id, name, price) values (150, 'Lettuce - California Mix', 23.1);
insert into products (id, name, price) values (151, 'Bread - Rolls, Corn', 20.27);
insert into products (id, name, price) values (152, 'Chips Potato All Dressed - 43g', 53.97);
insert into products (id, name, price) values (153, 'Mushroom - King Eryingii', 77.49);
insert into products (id, name, price) values (154, 'Turkey - Breast, Bone - In', 2.64);
insert into products (id, name, price) values (155, 'Soup - Base Broth Beef', 88.33);
insert into products (id, name, price) values (156, 'Mushroom - Enoki, Fresh', 63.18);
insert into products (id, name, price) values (157, 'Lemon Pepper', 36.22);
insert into products (id, name, price) values (158, 'Oil - Grapeseed Oil', 34.65);
insert into products (id, name, price) values (159, 'Muffin - Blueberry Individual', 1.26);
insert into products (id, name, price) values (160, 'Jicama', 23.75);
insert into products (id, name, price) values (161, 'Pop Shoppe Cream Soda', 23.81);
insert into products (id, name, price) values (162, 'Snapple - Iced Tea Peach', 15.67);
insert into products (id, name, price) values (163, 'Wine - Montecillo Rioja Crianza', 45.27);
insert into products (id, name, price) values (164, 'Squash - Pepper', 36.07);
insert into products (id, name, price) values (165, 'Brownies - Two Bite, Chocolate', 71.61);
insert into products (id, name, price) values (166, 'Arizona - Plum Green Tea', 29.84);
insert into products (id, name, price) values (167, 'Wine - Red, Black Opal Shiraz', 63.47);
insert into products (id, name, price) values (168, 'Extract - Lemon', 36.85);
insert into products (id, name, price) values (169, 'Steampan - Half Size Shallow', 62.55);
insert into products (id, name, price) values (170, 'Mountain Dew', 84.81);
insert into products (id, name, price) values (171, 'Sole - Dover, Whole, Fresh', 97.38);
insert into products (id, name, price) values (172, 'Potatoes - Purple, Organic', 78.14);
insert into products (id, name, price) values (173, 'Tomatoes - Vine Ripe, Red', 33.97);
insert into products (id, name, price) values (174, 'Puree - Mocha', 30.95);
insert into products (id, name, price) values (175, 'Quail - Whole, Boneless', 53.63);
insert into products (id, name, price) values (176, 'Fennel', 24.23);
insert into products (id, name, price) values (177, 'Cheese Cheddar Processed', 68.52);
insert into products (id, name, price) values (178, 'Sobe - Berry Energy', 87.48);
insert into products (id, name, price) values (179, 'Cheese - Woolwich Goat, Log', 4.66);
insert into products (id, name, price) values (180, 'Banana - Leaves', 93.57);
insert into products (id, name, price) values (181, 'Sping Loaded Cup Dispenser', 72.85);
insert into products (id, name, price) values (182, 'Cookie Dough - Chunky', 32.84);
insert into products (id, name, price) values (183, 'Bag Stand', 35.43);
insert into products (id, name, price) values (184, 'Ham - Procutinni', 60.8);
insert into products (id, name, price) values (185, 'Scallops - 20/30', 52.06);
insert into products (id, name, price) values (186, 'Bandage - Fexible 1x3', 26.5);
insert into products (id, name, price) values (187, 'Sprite, Diet - 355ml', 31.34);
insert into products (id, name, price) values (188, 'Jam - Blackberry, 20 Ml Jar', 80.67);
insert into products (id, name, price) values (189, 'Pasta - Rotini, Dry', 76.42);
insert into products (id, name, price) values (190, 'Rice - 7 Grain Blend', 85.37);
insert into products (id, name, price) values (191, 'Bread - Dark Rye', 9.46);
insert into products (id, name, price) values (192, 'Stainless Steel Cleaner Vision', 1.59);
insert into products (id, name, price) values (193, 'Bread - White, Unsliced', 43.57);
insert into products (id, name, price) values (194, 'Cup - Translucent 7 Oz Clear', 16.43);
insert into products (id, name, price) values (195, 'Berry Brulee', 33.51);
insert into products (id, name, price) values (196, 'Beans - French', 75.33);
insert into products (id, name, price) values (197, 'Ice Cream - Turtles Stick Bar', 27.89);
insert into products (id, name, price) values (198, 'Yogurt - Peach, 175 Gr', 26.42);
insert into products (id, name, price) values (199, 'Nantucket - Orange Mango Cktl', 31.87);
insert into products (id, name, price) values (200, 'Coffee Cup 8oz 5338cd', 35.18);
insert into products (id, name, price) values (201, 'Pear - Halves', 77.72);
insert into products (id, name, price) values (202, 'Yukon Jack', 75.01);
insert into products (id, name, price) values (203, 'Olives - Black, Pitted', 84.36);
insert into products (id, name, price) values (204, 'Napkin - Dinner, White', 15.73);
insert into products (id, name, price) values (205, 'Pumpkin - Seed', 59.29);
insert into products (id, name, price) values (206, 'Five Alive Citrus', 55.29);
insert into products (id, name, price) values (207, 'Danishes - Mini Cheese', 98.7);
insert into products (id, name, price) values (208, 'Goulash Seasoning', 82.81);
insert into products (id, name, price) values (209, 'Appetizer - Sausage Rolls', 82.23);
insert into products (id, name, price) values (210, 'Jameson Irish Whiskey', 22.69);
insert into products (id, name, price) values (211, 'Soup - Campbellschix Stew', 60.61);
insert into products (id, name, price) values (212, 'Aspic - Clear', 21.17);
insert into products (id, name, price) values (213, 'Water, Tap', 31.22);
insert into products (id, name, price) values (214, 'Beef - Short Loin', 89.5);
insert into products (id, name, price) values (215, 'Lettuce - Boston Bib', 61.6);
insert into products (id, name, price) values (216, 'Bagels Poppyseed', 51.47);
insert into products (id, name, price) values (217, 'Dragon Fruit', 7.83);
insert into products (id, name, price) values (218, 'Tia Maria', 56.02);
insert into products (id, name, price) values (219, 'Juice - Apple Cider', 16.87);
insert into products (id, name, price) values (220, 'Absolut Citron', 81.08);
insert into products (id, name, price) values (221, 'Yeast Dry - Fleischman', 57.75);
insert into products (id, name, price) values (222, 'Vermacelli - Sprinkles, Assorted', 63.99);
insert into products (id, name, price) values (223, 'Amarula Cream', 41.68);
insert into products (id, name, price) values (224, 'Lemonade - Mandarin, 591 Ml', 9.87);
insert into products (id, name, price) values (225, 'Dip - Tapenade', 88.89);
insert into products (id, name, price) values (226, 'Bread - Italian Sesame Poly', 48.22);
insert into products (id, name, price) values (227, 'Grenadine', 74.52);
insert into products (id, name, price) values (228, 'Yogurt - Raspberry, 175 Gr', 73.87);
insert into products (id, name, price) values (229, 'Tea - Honey Green Tea', 91.0);
insert into products (id, name, price) values (230, 'Bread - Roll, Whole Wheat', 71.64);
insert into products (id, name, price) values (231, 'Pears - Anjou', 56.74);
insert into products (id, name, price) values (232, 'Ice Cream - Chocolate', 99.43);
insert into products (id, name, price) values (233, 'Sweet Pea Sprouts', 73.09);
insert into products (id, name, price) values (234, 'Wine - Magnotta - Pinot Gris Sr', 93.66);
insert into products (id, name, price) values (235, 'Kellogs Special K Cereal', 91.87);
insert into products (id, name, price) values (236, 'Flour Dark Rye', 26.0);
insert into products (id, name, price) values (237, 'Tomato Paste', 64.71);
insert into products (id, name, price) values (238, 'Green Scrubbie Pad H.duty', 91.84);
insert into products (id, name, price) values (239, 'Lid - 16 Oz And 32 Oz', 90.16);
insert into products (id, name, price) values (240, 'Versatainer Nc - 9388', 58.82);
insert into products (id, name, price) values (241, 'Pasta - Lasagna, Dry', 27.12);
insert into products (id, name, price) values (242, 'Red Currants', 37.23);
insert into products (id, name, price) values (243, 'Table Cloth 54x72 Colour', 29.41);
insert into products (id, name, price) values (244, 'Coffee - Irish Cream', 36.42);
insert into products (id, name, price) values (245, 'Pastry - Carrot Muffin - Mini', 9.96);
insert into products (id, name, price) values (246, 'Wine - Rioja Campo Viejo', 95.06);
insert into products (id, name, price) values (247, 'Pepper - Red Bell', 27.65);
insert into products (id, name, price) values (248, 'Beans - Fava Fresh', 16.38);
insert into products (id, name, price) values (249, 'Lettuce - Mini Greens, Whole', 36.86);
insert into products (id, name, price) values (250, 'Tart Shells - Sweet, 3', 99.62);
insert into products (id, name, price) values (251, 'Pork - Back, Long Cut, Boneless', 6.07);
insert into products (id, name, price) values (252, 'Rolled Oats', 44.53);
insert into products (id, name, price) values (253, 'Beer - Sleemans Cream Ale', 20.05);
insert into products (id, name, price) values (254, 'Table Cloth 62x114 White', 74.44);
insert into products (id, name, price) values (255, 'Remy Red Berry Infusion', 74.85);
insert into products (id, name, price) values (256, 'Bread Crumbs - Japanese Style', 46.27);
insert into products (id, name, price) values (257, 'Skirt - 29 Foot', 57.37);
insert into products (id, name, price) values (258, 'Spinach - Packaged', 9.49);
insert into products (id, name, price) values (259, 'Wine - Magnotta - Bel Paese White', 70.99);
insert into products (id, name, price) values (260, 'Sauce - Hollandaise', 47.96);
insert into products (id, name, price) values (261, 'Knife Plastic - White', 82.34);
insert into products (id, name, price) values (262, 'Wine - Masi Valpolocell', 37.66);
insert into products (id, name, price) values (263, 'Napkin White - Starched', 5.69);
insert into products (id, name, price) values (264, 'Pasta - Rotini, Dry', 19.72);
insert into products (id, name, price) values (265, 'Wine - Pinot Noir Stoneleigh', 6.43);
insert into products (id, name, price) values (266, 'Bread - Burger', 85.32);
insert into products (id, name, price) values (267, 'Wine - Red, Gamay Noir', 30.66);
insert into products (id, name, price) values (268, 'Yogurt - Plain', 72.68);
insert into products (id, name, price) values (269, 'Muffin Carrot - Individual', 37.3);
insert into products (id, name, price) values (270, 'Sauce - Soy Low Sodium - 3.87l', 2.02);
insert into products (id, name, price) values (271, 'Yoghurt Tubes', 27.03);
insert into products (id, name, price) values (272, 'Ecolab - Medallion', 37.21);
insert into products (id, name, price) values (273, 'Pastry - Key Limepoppy Seed Tea', 97.03);
insert into products (id, name, price) values (274, 'Egg Patty Fried', 59.06);
insert into products (id, name, price) values (275, 'Chinese Foods - Plain Fried Rice', 20.44);
insert into products (id, name, price) values (276, 'Wine - Red, Pinot Noir, Chateau', 65.72);
insert into products (id, name, price) values (277, 'Cocoa Powder - Dutched', 38.82);
insert into products (id, name, price) values (278, 'Rosemary - Primerba, Paste', 41.69);
insert into products (id, name, price) values (279, 'Oil - Shortening - All - Purpose', 19.4);
insert into products (id, name, price) values (280, 'Lettuce - Belgian Endive', 60.26);
insert into products (id, name, price) values (281, 'Petit Baguette', 45.68);
insert into products (id, name, price) values (282, 'Crab - Blue, Frozen', 62.78);
insert into products (id, name, price) values (283, 'Kale - Red', 36.52);
insert into products (id, name, price) values (284, 'Cookies - Oreo, 4 Pack', 15.69);
insert into products (id, name, price) values (285, 'Wheat - Soft Kernal Of Wheat', 79.43);
insert into products (id, name, price) values (286, 'Tomatillo', 40.34);
insert into products (id, name, price) values (287, 'Soup - Campbells, Chix Gumbo', 1.66);
insert into products (id, name, price) values (288, 'Pasta - Rotini, Dry', 76.92);
insert into products (id, name, price) values (289, 'Cake - Miini Cheesecake Cherry', 45.0);
insert into products (id, name, price) values (290, 'Bread - Italian Corn Meal Poly', 9.27);
insert into products (id, name, price) values (291, 'Saskatoon Berries - Frozen', 11.31);
insert into products (id, name, price) values (292, 'Arctic Char - Fillets', 65.41);
insert into products (id, name, price) values (293, 'Tamarillo', 91.2);
insert into products (id, name, price) values (294, 'Pecan Raisin - Tarts', 74.98);
insert into products (id, name, price) values (295, 'Fruit Mix - Light', 21.8);
insert into products (id, name, price) values (296, 'Wine - Hardys Bankside Shiraz', 72.58);
insert into products (id, name, price) values (297, 'Roe - Lump Fish, Red', 46.48);
insert into products (id, name, price) values (298, 'Oregano - Fresh', 99.13);
insert into products (id, name, price) values (299, 'Beef - Salted', 13.45);
insert into products (id, name, price) values (300, 'Cheese - Asiago', 28.55);
insert into products (id, name, price) values (301, 'Mussels - Cultivated', 54.77);
insert into products (id, name, price) values (302, 'Carrots - Purple, Organic', 28.3);
insert into products (id, name, price) values (303, 'Muffin Orange Individual', 30.12);
insert into products (id, name, price) values (304, 'Sambuca Cream', 88.6);
insert into products (id, name, price) values (305, 'Pastry - Chocolate Chip Muffin', 33.74);
insert into products (id, name, price) values (306, 'Island Oasis - Banana Daiquiri', 47.84);
insert into products (id, name, price) values (307, 'Dc - Frozen Momji', 84.64);
insert into products (id, name, price) values (308, 'Puree - Blackcurrant', 26.85);
insert into products (id, name, price) values (309, 'Pepper - Orange', 83.76);
insert into products (id, name, price) values (310, 'Mint - Fresh', 13.68);
insert into products (id, name, price) values (311, 'Flour - Bread', 74.98);
insert into products (id, name, price) values (312, 'Bread - Raisin Walnut Oval', 36.4);
insert into products (id, name, price) values (313, 'Longos - Chicken Caeser Salad', 94.77);
insert into products (id, name, price) values (314, 'Soup - Campbells Beef Noodle', 48.64);
insert into products (id, name, price) values (315, 'Tomato - Tricolor Cherry', 25.36);
insert into products (id, name, price) values (316, 'Syrup - Monin, Irish Cream', 14.48);
insert into products (id, name, price) values (317, 'Bread - Italian Sesame Poly', 1.23);
insert into products (id, name, price) values (318, 'Meldea Green Tea Liquor', 53.18);
insert into products (id, name, price) values (319, 'Beef - Top Butt', 72.31);
insert into products (id, name, price) values (320, 'Wine - Winzer Krems Gruner', 92.12);
insert into products (id, name, price) values (321, 'Beef - Top Sirloin - Aaa', 29.99);
insert into products (id, name, price) values (322, 'Turnip - Wax', 35.26);
insert into products (id, name, price) values (323, 'Beef Cheek Fresh', 48.89);
insert into products (id, name, price) values (324, 'Pate - Cognac', 57.25);
insert into products (id, name, price) values (325, 'Table Cloth 120 Round White', 46.38);
insert into products (id, name, price) values (326, 'Wine - Prosecco Valdobienne', 79.91);
insert into products (id, name, price) values (327, 'Sobe - Lizard Fuel', 69.57);
insert into products (id, name, price) values (328, 'Salmon - Atlantic, No Skin', 14.49);
insert into products (id, name, price) values (329, 'Wine - Mas Chicet Rose, Vintage', 46.25);
insert into products (id, name, price) values (330, 'Initation Crab Meat', 10.07);
insert into products (id, name, price) values (331, 'Bread - Onion Focaccia', 51.54);
insert into products (id, name, price) values (332, 'Sea Urchin', 48.16);
insert into products (id, name, price) values (333, 'Assorted Desserts', 9.27);
insert into products (id, name, price) values (334, 'Flour - All Purpose', 24.35);
insert into products (id, name, price) values (335, 'Flour - Chickpea', 54.6);
insert into products (id, name, price) values (336, 'Pickles - Gherkins', 17.34);
insert into products (id, name, price) values (337, 'Veal Inside - Provimi', 6.62);
insert into products (id, name, price) values (338, 'Puree - Pear', 91.52);
insert into products (id, name, price) values (339, 'True - Vue Containers', 9.9);
insert into products (id, name, price) values (340, 'Pepper - Black, Whole', 50.81);
insert into products (id, name, price) values (341, 'Bread Bowl Plain', 64.55);
insert into products (id, name, price) values (342, 'Rice Wine - Aji Mirin', 80.91);
insert into products (id, name, price) values (343, 'Lumpfish Black', 65.53);
insert into products (id, name, price) values (344, 'Pastry - Cheese Baked Scones', 49.85);
insert into products (id, name, price) values (345, 'Ice Cream - Life Savers', 54.78);
insert into products (id, name, price) values (346, 'Oven Mitt - 13 Inch', 72.04);
insert into products (id, name, price) values (347, 'Chips Potato Swt Chilli Sour', 48.68);
insert into products (id, name, price) values (348, 'Sauce - Caesar Dressing', 30.05);
insert into products (id, name, price) values (349, 'Lobster - Cooked', 17.25);
insert into products (id, name, price) values (350, 'Beef - Tender Tips', 55.19);
insert into products (id, name, price) values (351, 'Sauce - Gravy, Au Jus, Mix', 52.36);
insert into products (id, name, price) values (352, 'Cafe Royale', 49.15);
insert into products (id, name, price) values (353, 'Turnip - White, Organic', 51.24);
insert into products (id, name, price) values (354, 'Sausage - Blood Pudding', 23.03);
insert into products (id, name, price) values (355, 'Wine - Lamancha Do Crianza', 21.37);
insert into products (id, name, price) values (356, 'Nescafe - Frothy French Vanilla', 84.97);
insert into products (id, name, price) values (357, 'Wine - Tribal Sauvignon', 22.1);
insert into products (id, name, price) values (358, 'Peas - Frozen', 91.41);
insert into products (id, name, price) values (359, 'Coffee - Egg Nog Capuccino', 84.89);
insert into products (id, name, price) values (360, 'Spring Roll Veg Mini', 56.25);
insert into products (id, name, price) values (361, 'Chambord Royal', 57.71);
insert into products (id, name, price) values (362, 'Sour Cream', 76.69);
insert into products (id, name, price) values (363, 'Bread Base - Toscano', 48.54);
insert into products (id, name, price) values (364, 'Roe - Lump Fish, Black', 33.08);
insert into products (id, name, price) values (365, 'Blueberries', 35.37);
insert into products (id, name, price) values (366, 'Bag - Bread, White, Plain', 98.16);
insert into products (id, name, price) values (367, 'Sauce - Salsa', 77.46);
insert into products (id, name, price) values (368, 'Shrimp, Dried, Small / Lb', 37.93);
insert into products (id, name, price) values (369, 'Soup - Campbells Beef Stew', 53.33);
insert into products (id, name, price) values (370, 'Muffin Chocolate Individual Wrap', 53.58);
insert into products (id, name, price) values (371, 'Pork - Liver', 97.02);
insert into products (id, name, price) values (372, 'Bread - Bistro White', 2.05);
insert into products (id, name, price) values (373, 'Cabbage - Red', 85.55);
insert into products (id, name, price) values (374, 'Basil - Dry, Rubbed', 27.53);
insert into products (id, name, price) values (375, 'Tahini Paste', 70.19);
insert into products (id, name, price) values (376, 'Pork Casing', 82.45);
insert into products (id, name, price) values (377, 'Bread - Frozen Basket Variety', 53.33);
insert into products (id, name, price) values (378, 'Chicken - Base', 2.12);
insert into products (id, name, price) values (379, 'Wine - Rubyport', 16.2);
insert into products (id, name, price) values (380, 'Beans - Kidney, Red Dry', 1.09);
insert into products (id, name, price) values (381, 'Compound - Orange', 36.46);
insert into products (id, name, price) values (382, 'Anchovy In Oil', 98.4);
insert into products (id, name, price) values (383, 'Pasta - Lasagna, Dry', 42.79);
insert into products (id, name, price) values (384, 'Mayonnaise - Individual Pkg', 9.47);
insert into products (id, name, price) values (385, 'Lemonade - Black Cherry, 591 Ml', 71.89);
insert into products (id, name, price) values (386, 'Pomegranates', 57.49);
insert into products (id, name, price) values (387, 'Persimmons', 30.92);
insert into products (id, name, price) values (388, 'Pork - Smoked Kassler', 41.25);
insert into products (id, name, price) values (389, 'Lettuce - Mini Greens, Whole', 66.23);
insert into products (id, name, price) values (390, 'Tomatoes - Plum, Canned', 27.8);
insert into products (id, name, price) values (391, 'Raspberries - Frozen', 66.8);
insert into products (id, name, price) values (392, 'Longos - Grilled Veg Sandwiches', 31.11);
insert into products (id, name, price) values (393, 'Soup - Campbells, Creamy', 47.99);
insert into products (id, name, price) values (394, 'Water - Mineral, Natural', 52.74);
insert into products (id, name, price) values (395, 'Juice - Tomato, 10 Oz', 3.7);
insert into products (id, name, price) values (396, 'Bar Mix - Pina Colada, 355 Ml', 50.09);
insert into products (id, name, price) values (397, 'Butter Balls Salted', 66.76);
insert into products (id, name, price) values (398, 'Beef - Striploin', 68.46);
insert into products (id, name, price) values (399, 'Pork Salted Bellies', 54.81);
insert into products (id, name, price) values (400, 'Baking Soda', 88.82);
insert into products (id, name, price) values (401, 'Cheese - Cream Cheese', 76.9);
insert into products (id, name, price) values (402, 'Lemon Tarts', 64.56);
insert into products (id, name, price) values (403, 'Parsley - Dried', 2.23);
insert into products (id, name, price) values (404, 'Goat - Leg', 48.09);
insert into products (id, name, price) values (405, 'Ostrich - Fan Fillet', 52.89);
insert into products (id, name, price) values (406, 'Butter Balls Salted', 15.22);
insert into products (id, name, price) values (407, 'Pastry - Baked Cinnamon Stick', 28.46);
insert into products (id, name, price) values (408, 'Flower - Commercial Bronze', 96.46);
insert into products (id, name, price) values (409, 'Olive - Spread Tapenade', 29.8);
insert into products (id, name, price) values (410, 'Cheese - Sheep Milk', 66.46);
insert into products (id, name, price) values (411, 'Cherries - Maraschino,jar', 88.15);
insert into products (id, name, price) values (412, 'Wine - Two Oceans Cabernet', 50.0);
insert into products (id, name, price) values (413, 'Beef - Kobe Striploin', 20.1);
insert into products (id, name, price) values (414, 'Lobster - Cooked', 68.25);
insert into products (id, name, price) values (415, 'Beer - Steamwhistle', 88.04);
insert into products (id, name, price) values (416, 'Bread - Roll, Calabrese', 21.61);
insert into products (id, name, price) values (417, 'Napkin - Dinner, White', 30.52);
insert into products (id, name, price) values (418, 'Broom - Corn', 59.08);
insert into products (id, name, price) values (419, 'Table Cloth 62x114 White', 56.7);
insert into products (id, name, price) values (420, 'Kellogs Cereal In A Cup', 31.26);
insert into products (id, name, price) values (421, 'Energy Drink Red Bull', 8.39);
insert into products (id, name, price) values (422, 'Jerusalem Artichoke', 13.75);
insert into products (id, name, price) values (423, 'Calypso - Lemonade', 23.47);
insert into products (id, name, price) values (424, 'Sauce - Salsa', 39.84);
insert into products (id, name, price) values (425, 'Juice - Pineapple, 48 Oz', 52.15);
insert into products (id, name, price) values (426, 'Creme De Menth - White', 82.17);
insert into products (id, name, price) values (427, 'Bols Melon Liqueur', 11.85);
insert into products (id, name, price) values (428, 'Water - Spring Water 500ml', 87.57);
insert into products (id, name, price) values (429, 'Juice - Lemon', 92.85);
insert into products (id, name, price) values (430, 'Sugar - Sweet N Low, Individual', 58.26);
insert into products (id, name, price) values (431, 'Aspic - Amber', 52.92);
insert into products (id, name, price) values (432, 'Cakes Assorted', 14.86);
insert into products (id, name, price) values (433, 'Garam Masala Powder', 70.26);
insert into products (id, name, price) values (434, 'Water - Spring Water, 355 Ml', 79.98);
insert into products (id, name, price) values (435, 'Cheese - Parmesan Grated', 34.81);
insert into products (id, name, price) values (436, 'Quail - Whole, Boneless', 68.17);
insert into products (id, name, price) values (437, 'Chestnuts - Whole,canned', 72.81);
insert into products (id, name, price) values (438, 'Pork - Tenderloin, Fresh', 56.86);
insert into products (id, name, price) values (439, 'Star Fruit', 98.47);
insert into products (id, name, price) values (440, 'Wine - Magnotta - Cab Sauv', 38.08);
insert into products (id, name, price) values (441, 'Bread - Triangle White', 11.48);
insert into products (id, name, price) values (442, 'Mousse - Banana Chocolate', 22.12);
insert into products (id, name, price) values (443, 'Pepper - Black, Ground', 97.12);
insert into products (id, name, price) values (444, 'Cape Capensis - Fillet', 98.29);
insert into products (id, name, price) values (445, 'Vinegar - Red Wine', 28.62);
insert into products (id, name, price) values (446, 'Beets - Candy Cane, Organic', 34.58);
insert into products (id, name, price) values (447, 'Wine - White, Pelee Island', 54.72);
insert into products (id, name, price) values (448, 'Lamb - Loin, Trimmed, Boneless', 45.63);
insert into products (id, name, price) values (449, 'Truffle Cups - Brown', 15.28);
insert into products (id, name, price) values (450, 'Soup - Beef, Base Mix', 73.72);
insert into products (id, name, price) values (451, 'Limes', 48.51);
insert into products (id, name, price) values (452, 'Cabbage - Red', 82.76);
insert into products (id, name, price) values (453, 'Potatoes - Pei 10 Oz', 8.29);
insert into products (id, name, price) values (454, 'Spinach - Frozen', 72.15);
insert into products (id, name, price) values (455, 'Mushroom - Chanterelle Frozen', 17.11);
insert into products (id, name, price) values (456, 'Cheese - Havarti, Salsa', 99.75);
insert into products (id, name, price) values (457, 'Beef - Flank Steak', 84.01);
insert into products (id, name, price) values (458, 'Appetizer - Mango Chevre', 52.4);
insert into products (id, name, price) values (459, 'Gelatine Leaves - Bulk', 21.38);
insert into products (id, name, price) values (460, 'Chinese Foods - Pepper Beef', 34.77);
insert into products (id, name, price) values (461, 'Veal - Inside, Choice', 80.2);
insert into products (id, name, price) values (462, 'Red Currant Jelly', 25.71);
insert into products (id, name, price) values (463, 'Crackers - Melba Toast', 26.45);
insert into products (id, name, price) values (464, 'Hummus - Spread', 22.64);
insert into products (id, name, price) values (465, 'Wine - Blue Nun Qualitatswein', 89.74);
insert into products (id, name, price) values (466, 'Plastic Wrap', 29.91);
insert into products (id, name, price) values (467, 'Nestea - Ice Tea, Diet', 93.06);
insert into products (id, name, price) values (468, 'Coconut Milk - Unsweetened', 40.62);
insert into products (id, name, price) values (469, 'Pasta - Linguini, Dry', 73.75);
insert into products (id, name, price) values (470, 'Flower - Dish Garden', 38.97);
insert into products (id, name, price) values (471, 'Cheese - St. Paulin', 22.9);
insert into products (id, name, price) values (472, 'Mushroom Morel Fresh', 81.73);
insert into products (id, name, price) values (473, 'Sponge Cake Mix - Vanilla', 80.58);
insert into products (id, name, price) values (474, 'Pepper - Chipotle, Canned', 98.24);
insert into products (id, name, price) values (475, 'Mix - Cappucino Cocktail', 6.35);
insert into products (id, name, price) values (476, 'Goulash Seasoning', 12.46);
insert into products (id, name, price) values (477, 'Soup - Cream Of Broccoli, Dry', 50.92);
insert into products (id, name, price) values (478, 'Wine - White, Mosel Gold', 12.1);
insert into products (id, name, price) values (479, 'Tofu - Firm', 84.57);
insert into products (id, name, price) values (480, 'Rice - Sushi', 43.89);
insert into products (id, name, price) values (481, 'Coffee - 10oz Cup 92961', 7.37);
insert into products (id, name, price) values (482, 'Mushroom - Trumpet, Dry', 6.21);
insert into products (id, name, price) values (483, 'Squid - Breaded', 39.08);
insert into products (id, name, price) values (484, 'Turkey - Whole, Fresh', 23.8);
insert into products (id, name, price) values (485, 'Garlic', 45.05);
insert into products (id, name, price) values (486, 'Wine - Champagne Brut Veuve', 11.2);
insert into products (id, name, price) values (487, 'Foam Cup 6 Oz', 44.63);
insert into products (id, name, price) values (488, 'Pail For Lid 1537', 65.0);
insert into products (id, name, price) values (489, 'Aromat Spice / Seasoning', 97.2);
insert into products (id, name, price) values (490, 'Long Island Ice Tea', 13.02);
insert into products (id, name, price) values (491, 'Towel Dispenser', 26.38);
insert into products (id, name, price) values (492, 'Wine - Marlbourough Sauv Blanc', 30.44);
insert into products (id, name, price) values (493, 'Wine - Sogrape Mateus Rose', 39.17);
insert into products (id, name, price) values (494, 'Cheese - Woolwich Goat, Log', 18.47);
insert into products (id, name, price) values (495, 'Wine - Bouchard La Vignee Pinot', 59.22);
insert into products (id, name, price) values (496, 'Lamb - Whole, Fresh', 39.2);
insert into products (id, name, price) values (497, 'Sauce - Caesar Dressing', 47.87);
insert into products (id, name, price) values (498, 'Zucchini - Yellow', 55.61);
insert into products (id, name, price) values (499, 'Foil - Round Foil', 11.33);
insert into products (id, name, price) values (500, 'Sauce - Vodka Blush', 29.53);
insert into products (id, name, price) values (501, 'Kellogs Raisan Bran Bars', 46.36);
insert into products (id, name, price) values (502, 'Lid Coffee Cup 8oz Blk', 15.98);
insert into products (id, name, price) values (503, 'Yams', 76.5);
insert into products (id, name, price) values (504, 'Split Peas - Yellow, Dry', 31.75);
insert into products (id, name, price) values (505, 'Milk - Condensed', 29.35);
insert into products (id, name, price) values (506, 'Salmon Steak - Cohoe 6 Oz', 4.57);
insert into products (id, name, price) values (507, 'Apple - Granny Smith', 74.35);
insert into products (id, name, price) values (508, 'Gelatine Powder', 64.46);
insert into products (id, name, price) values (509, 'Pickles - Gherkins', 26.62);
insert into products (id, name, price) values (510, 'Knife Plastic - White', 14.49);
insert into products (id, name, price) values (511, 'Chocolate - Semi Sweet', 78.94);
insert into products (id, name, price) values (512, 'Pork - Bacon,back Peameal', 63.45);
insert into products (id, name, price) values (513, 'Vermouth - White, Cinzano', 79.25);
insert into products (id, name, price) values (514, 'Jameson - Irish Whiskey', 71.95);
insert into products (id, name, price) values (515, 'Wine - Fino Tio Pepe Gonzalez', 20.17);
insert into products (id, name, price) values (516, 'Horseradish Root', 4.39);
insert into products (id, name, price) values (517, 'Lid Coffee Cup 8oz Blk', 90.14);
insert into products (id, name, price) values (518, 'Nut - Cashews, Whole, Raw', 16.57);
insert into products (id, name, price) values (519, 'Bagels Poppyseed', 20.44);
insert into products (id, name, price) values (520, 'Carbonated Water - Orange', 92.87);
insert into products (id, name, price) values (521, 'Bread - Rolls, Rye', 58.51);
insert into products (id, name, price) values (522, 'Water - Spring Water 500ml', 92.33);
insert into products (id, name, price) values (523, 'Pie Filling - Pumpkin', 8.48);
insert into products (id, name, price) values (524, 'Crush - Cream Soda', 13.11);
insert into products (id, name, price) values (525, 'Ham - Proscuitto', 85.19);
insert into products (id, name, price) values (526, 'Mushroom Morel Fresh', 72.81);
insert into products (id, name, price) values (527, 'Croissants Thaw And Serve', 60.6);
insert into products (id, name, price) values (528, 'Calypso - Strawberry Lemonade', 34.22);
insert into products (id, name, price) values (529, 'White Fish - Filets', 1.79);
insert into products (id, name, price) values (530, 'Table Cloth 72x144 White', 18.05);
insert into products (id, name, price) values (531, 'Juice - Lemon', 5.04);
insert into products (id, name, price) values (532, 'Pop Shoppe Cream Soda', 79.98);
insert into products (id, name, price) values (533, 'Crackers - Soda / Saltins', 84.48);
insert into products (id, name, price) values (534, 'Cookie Chocolate Chip With', 36.03);
insert into products (id, name, price) values (535, 'Turnip - Mini', 48.15);
insert into products (id, name, price) values (536, 'Pasta - Spaghetti, Dry', 53.83);
insert into products (id, name, price) values (537, 'Sherry - Dry', 56.3);
insert into products (id, name, price) values (538, 'Wine - Pinot Grigio Collavini', 28.66);
insert into products (id, name, price) values (539, 'Island Oasis - Magarita Mix', 87.09);
insert into products (id, name, price) values (540, 'Fish - Base, Bouillion', 58.57);
insert into products (id, name, price) values (541, 'Sauce - Salsa', 61.53);
insert into products (id, name, price) values (542, 'Pork - Belly Fresh', 26.05);
insert into products (id, name, price) values (543, 'Bread - Olive', 87.81);
insert into products (id, name, price) values (544, 'Beef - Salted', 97.76);
insert into products (id, name, price) values (545, 'Lettuce - Romaine, Heart', 78.7);
insert into products (id, name, price) values (546, 'Pastry - Banana Muffin - Mini', 99.77);
insert into products (id, name, price) values (547, 'Creme De Cacao Mcguines', 22.88);
insert into products (id, name, price) values (548, 'Veal - Tenderloin, Untrimmed', 10.55);
insert into products (id, name, price) values (549, 'Carbonated Water - Raspberry', 28.61);
insert into products (id, name, price) values (550, 'Parsley Italian - Fresh', 94.66);
insert into products (id, name, price) values (551, 'Breakfast Quesadillas', 12.67);
insert into products (id, name, price) values (552, 'Cookie Double Choco', 69.6);
insert into products (id, name, price) values (553, 'Pork - Sausage, Medium', 78.34);
insert into products (id, name, price) values (554, 'Phyllo Dough', 72.67);
insert into products (id, name, price) values (555, 'Bread - Bistro White', 2.35);
insert into products (id, name, price) values (556, 'Beer - Creemore', 51.84);
insert into products (id, name, price) values (557, 'Cod - Black Whole Fillet', 49.35);
insert into products (id, name, price) values (558, 'Chocolate Bar - Smarties', 94.12);
insert into products (id, name, price) values (559, 'Puree - Kiwi', 37.59);
insert into products (id, name, price) values (560, 'Beer - Sleeman Fine Porter', 47.31);
insert into products (id, name, price) values (561, 'Cheese - Grie Des Champ', 93.52);
insert into products (id, name, price) values (562, 'Pork - Ground', 13.68);
insert into products (id, name, price) values (563, 'Sesame Seed', 34.23);
insert into products (id, name, price) values (564, 'Wine - Gato Negro Cabernet', 88.58);
insert into products (id, name, price) values (565, 'Peas Snow', 13.41);
insert into products (id, name, price) values (566, 'Carbonated Water - Blackcherry', 26.93);
insert into products (id, name, price) values (567, 'Energy Drink Red Bull', 83.19);
insert into products (id, name, price) values (568, 'Coffee Cup 12oz 5342cd', 97.78);
insert into products (id, name, price) values (569, 'Napkin White - Starched', 79.49);
insert into products (id, name, price) values (570, 'Cheese - Havarti, Roasted Garlic', 76.77);
insert into products (id, name, price) values (571, 'Juice - Grapefruit, 341 Ml', 3.36);
insert into products (id, name, price) values (572, 'Chambord Royal', 74.46);
insert into products (id, name, price) values (573, 'Bread Country Roll', 77.59);
insert into products (id, name, price) values (574, 'Pastry - Key Limepoppy Seed Tea', 57.42);
insert into products (id, name, price) values (575, 'Pasta - Gnocchi, Potato', 65.54);
insert into products (id, name, price) values (576, 'Soup - Base Broth Chix', 17.78);
insert into products (id, name, price) values (577, 'Wine - Cotes Du Rhone Parallele', 54.36);
insert into products (id, name, price) values (578, 'Calypso - Black Cherry Lemonade', 95.59);
insert into products (id, name, price) values (579, 'Marsala - Sperone, Fine, D.o.c.', 12.47);
insert into products (id, name, price) values (580, 'C - Plus, Orange', 75.51);
insert into products (id, name, price) values (581, 'Cattail Hearts', 86.58);
insert into products (id, name, price) values (582, 'Turkey - Breast, Bone - In', 54.13);
insert into products (id, name, price) values (583, 'Watercress', 31.37);
insert into products (id, name, price) values (584, 'Pork Loin Cutlets', 98.87);
insert into products (id, name, price) values (585, 'Cheese - Parmigiano Reggiano', 24.52);
insert into products (id, name, price) values (586, 'Energy Drink', 60.45);
insert into products (id, name, price) values (587, 'Milk - 2% 250 Ml', 23.21);
insert into products (id, name, price) values (588, 'Sproutsmustard Cress', 28.31);
insert into products (id, name, price) values (589, 'Beef - Eye Of Round', 27.3);
insert into products (id, name, price) values (590, 'Wine - Red, Mouton Cadet', 56.63);
insert into products (id, name, price) values (591, 'Rabbit - Frozen', 54.61);
insert into products (id, name, price) values (592, 'Triple Sec - Mcguinness', 10.59);
insert into products (id, name, price) values (593, 'Flavouring - Orange', 6.86);
insert into products (id, name, price) values (594, 'Liners - Baking Cups', 97.76);
insert into products (id, name, price) values (595, 'Extract - Raspberry', 32.6);
insert into products (id, name, price) values (596, 'Chef Hat 20cm', 60.16);
insert into products (id, name, price) values (597, 'Tomato - Plum With Basil', 1.56);
insert into products (id, name, price) values (598, 'Maple Syrup', 28.08);
insert into products (id, name, price) values (599, 'Limes', 56.01);
insert into products (id, name, price) values (600, 'Wine - Domaine Boyar Royal', 53.51);
insert into products (id, name, price) values (601, 'Croissants Thaw And Serve', 20.58);
insert into products (id, name, price) values (602, 'Turkey - Ground. Lean', 30.57);
insert into products (id, name, price) values (603, 'Alize Gold Passion', 37.76);
insert into products (id, name, price) values (604, 'Apples - Sliced / Wedge', 60.41);
insert into products (id, name, price) values (605, 'Vinegar - White Wine', 38.42);
insert into products (id, name, price) values (606, 'Water - San Pellegrino', 5.02);
insert into products (id, name, price) values (607, 'Squash - Acorn', 61.94);
insert into products (id, name, price) values (608, 'Hummus - Spread', 85.3);
insert into products (id, name, price) values (609, 'Beef - Salted', 47.51);
insert into products (id, name, price) values (610, 'Fruit Mix - Light', 97.58);
insert into products (id, name, price) values (611, 'Eggroll', 62.94);
insert into products (id, name, price) values (612, 'Isomalt', 45.88);
insert into products (id, name, price) values (613, 'Shrimp - Black Tiger 13/15', 55.35);
insert into products (id, name, price) values (614, 'Leeks - Large', 56.59);
insert into products (id, name, price) values (615, 'Foam Tray S2', 2.32);
insert into products (id, name, price) values (616, 'Pastry - Chocolate Marble Tea', 43.54);
insert into products (id, name, price) values (617, 'Filter - Coffee', 29.06);
insert into products (id, name, price) values (618, 'Lamb - Leg, Bone In', 87.9);
insert into products (id, name, price) values (619, 'Syrup - Chocolate', 87.45);
insert into products (id, name, price) values (620, 'Appetizer - Spring Roll, Veg', 36.51);
insert into products (id, name, price) values (621, 'Cheese - Marble', 50.45);
insert into products (id, name, price) values (622, 'Evaporated Milk - Skim', 90.7);
insert into products (id, name, price) values (623, 'Asparagus - Mexican', 42.4);
insert into products (id, name, price) values (624, 'Oil - Olive Bertolli', 53.82);
insert into products (id, name, price) values (625, 'Heavy Duty Dust Pan', 5.09);
insert into products (id, name, price) values (626, 'Kohlrabi', 28.94);
insert into products (id, name, price) values (627, 'Graham Cracker Mix', 71.4);
insert into products (id, name, price) values (628, 'Pasta - Spaghetti, Dry', 88.37);
insert into products (id, name, price) values (629, 'Bacardi Mojito', 78.37);
insert into products (id, name, price) values (630, 'Soup Campbells', 79.16);
insert into products (id, name, price) values (631, 'Energy - Boo - Koo', 45.1);
insert into products (id, name, price) values (632, 'The Pop Shoppe - Cream Soda', 25.6);
insert into products (id, name, price) values (633, 'Chervil - Fresh', 40.73);
insert into products (id, name, price) values (634, 'Wine - Piper Heidsieck Brut', 69.26);
insert into products (id, name, price) values (635, 'Pears - Anjou', 78.37);
insert into products (id, name, price) values (636, 'Wine - Delicato Merlot', 63.27);
insert into products (id, name, price) values (637, 'Bread - Raisin Walnut Pull', 28.35);
insert into products (id, name, price) values (638, 'Bread - Raisin Walnut Oval', 23.23);
insert into products (id, name, price) values (639, 'Bread - Bagels, Mini', 29.3);
insert into products (id, name, price) values (640, 'Sprouts - Corn', 67.79);
insert into products (id, name, price) values (641, 'Wine - Pinot Noir Pond Haddock', 46.35);
insert into products (id, name, price) values (642, 'Liqueur - Melon', 43.32);
insert into products (id, name, price) values (643, 'Bread - Multigrain', 21.37);
insert into products (id, name, price) values (644, 'Pasta - Cannelloni, Sheets, Fresh', 26.61);
insert into products (id, name, price) values (645, 'Chip - Potato Dill Pickle', 31.18);
insert into products (id, name, price) values (646, 'Sea Urchin', 19.86);
insert into products (id, name, price) values (647, 'Veal - Insides, Grains', 14.06);
insert into products (id, name, price) values (648, 'Soup - Campbells Broccoli', 63.76);
insert into products (id, name, price) values (649, 'Pork - Tenderloin, Fresh', 40.34);
insert into products (id, name, price) values (650, 'Mushroom Morel Fresh', 83.6);
insert into products (id, name, price) values (651, 'Glass - Juice Clear 5oz 55005', 9.84);
insert into products (id, name, price) values (652, 'Sprouts - Bean', 2.79);
insert into products (id, name, price) values (653, 'Cabbage Roll', 19.37);
insert into products (id, name, price) values (654, 'Wine - Alicanca Vinho Verde', 41.31);
insert into products (id, name, price) values (655, 'Mushroom - Chanterelle, Dry', 91.69);
insert into products (id, name, price) values (656, 'Cheese - Goat', 40.57);
insert into products (id, name, price) values (657, 'Oil - Margarine', 1.25);
insert into products (id, name, price) values (658, 'Sauce - Apple, Unsweetened', 29.36);
insert into products (id, name, price) values (659, 'Oil - Olive, Extra Virgin', 70.51);
insert into products (id, name, price) values (660, 'Carbonated Water - Raspberry', 17.0);
insert into products (id, name, price) values (661, 'Bread - Triangle White', 17.38);
insert into products (id, name, price) values (662, 'Ham - Cooked Bayonne Tinned', 11.75);
insert into products (id, name, price) values (663, 'Pear - Asian', 90.98);
insert into products (id, name, price) values (664, 'Papadam', 95.73);
insert into products (id, name, price) values (665, 'Wiberg Cure', 96.57);
insert into products (id, name, price) values (666, 'Curry Paste - Green Masala', 74.99);
insert into products (id, name, price) values (667, 'Bread - Sour Sticks With Onion', 15.82);
insert into products (id, name, price) values (668, 'Pork - Loin, Boneless', 35.74);
insert into products (id, name, price) values (669, 'Cardamon Ground', 55.04);
insert into products (id, name, price) values (670, 'Muffin Mix - Carrot', 62.61);
insert into products (id, name, price) values (671, 'Shrimp - Black Tiger 26/30', 55.39);
insert into products (id, name, price) values (672, 'Wine - White, Riesling, Henry Of', 5.95);
insert into products (id, name, price) values (673, 'Foil - Round Foil', 18.99);
insert into products (id, name, price) values (674, 'Cinnamon - Stick', 65.68);
insert into products (id, name, price) values (675, 'Dill Weed - Dry', 34.39);
insert into products (id, name, price) values (676, 'Dasheen', 18.06);
insert into products (id, name, price) values (677, 'Wine - White, Ej Gallo', 92.95);
insert into products (id, name, price) values (678, 'Mince Meat - Filling', 58.41);
insert into products (id, name, price) values (679, 'Ham - Procutinni', 40.33);
insert into products (id, name, price) values (680, 'Bay Leaf Fresh', 17.95);
insert into products (id, name, price) values (681, 'Pears - Bosc', 88.36);
insert into products (id, name, price) values (682, 'Dill Weed - Dry', 78.82);
insert into products (id, name, price) values (683, 'Nut - Almond, Blanched, Sliced', 60.15);
insert into products (id, name, price) values (684, 'Milk - Chocolate 250 Ml', 93.1);
insert into products (id, name, price) values (685, 'Wine - Rhine Riesling Wolf Blass', 29.49);
insert into products (id, name, price) values (686, 'Bread - Italian Corn Meal Poly', 73.06);
insert into products (id, name, price) values (687, 'Veal - Insides Provini', 84.02);
insert into products (id, name, price) values (688, 'Spring Roll Wrappers', 49.93);
insert into products (id, name, price) values (689, 'Sauce - Black Current, Dry Mix', 5.77);
insert into products (id, name, price) values (690, 'Table Cloth 91x91 Colour', 41.99);
insert into products (id, name, price) values (691, 'Cup - Translucent 7 Oz Clear', 71.48);
insert into products (id, name, price) values (692, 'Sauce - White, Mix', 52.75);
insert into products (id, name, price) values (693, 'Meldea Green Tea Liquor', 48.22);
insert into products (id, name, price) values (694, 'Bread Roll Foccacia', 2.94);
insert into products (id, name, price) values (695, 'Coffee - Frthy Coffee Crisp', 7.96);
insert into products (id, name, price) values (696, 'Asparagus - White, Canned', 52.16);
insert into products (id, name, price) values (697, 'Crab - Dungeness, Whole, live', 8.56);
insert into products (id, name, price) values (698, 'Miso Paste White', 63.98);
insert into products (id, name, price) values (699, 'Pasta - Ravioli', 98.52);
insert into products (id, name, price) values (700, 'Steampan - Half Size Shallow', 36.22);
insert into products (id, name, price) values (701, 'Sauce - Roasted Red Pepper', 35.25);
insert into products (id, name, price) values (702, 'Madeira', 88.83);
insert into products (id, name, price) values (703, 'Monkfish - Fresh', 43.13);
insert into products (id, name, price) values (704, 'Durian Fruit', 82.52);
insert into products (id, name, price) values (705, 'Mace', 75.52);
insert into products (id, name, price) values (706, 'Tortillas - Flour, 10', 46.48);
insert into products (id, name, price) values (707, 'Capon - Breast, Wing On', 44.33);
insert into products (id, name, price) values (708, 'Star Anise, Whole', 47.25);
insert into products (id, name, price) values (709, 'Chicken - Livers', 42.79);
insert into products (id, name, price) values (710, 'Soup - French Onion', 72.9);
insert into products (id, name, price) values (711, 'Sauce - Soya, Light', 26.22);
insert into products (id, name, price) values (712, 'Oil - Olive Bertolli', 66.25);
insert into products (id, name, price) values (713, 'Sage Derby', 35.31);
insert into products (id, name, price) values (714, 'Soho Lychee Liqueur', 21.09);
insert into products (id, name, price) values (715, 'Wine - Pinot Noir Latour', 11.97);
insert into products (id, name, price) values (716, 'Pork - Kidney', 84.14);
insert into products (id, name, price) values (717, 'Tea - Mint', 60.66);
insert into products (id, name, price) values (718, 'Sauce Bbq Smokey', 57.18);
insert into products (id, name, price) values (719, 'Pork Salted Bellies', 49.63);
insert into products (id, name, price) values (720, 'Glycerine', 36.14);
insert into products (id, name, price) values (721, 'Bacardi Limon', 65.48);
insert into products (id, name, price) values (722, 'Cornstarch', 70.13);
insert into products (id, name, price) values (723, 'Capon - Breast, Double, Wing On', 9.4);
insert into products (id, name, price) values (724, 'Container - Clear 32 Oz', 36.21);
insert into products (id, name, price) values (725, 'Pasta - Tortellini, Fresh', 93.55);
insert into products (id, name, price) values (726, 'Fruit Mix - Light', 10.04);
insert into products (id, name, price) values (727, 'Pepper - Scotch Bonnet', 98.53);
insert into products (id, name, price) values (728, 'Urban Zen Drinks', 30.43);
insert into products (id, name, price) values (729, 'Wine - White, Riesling, Semi - Dry', 92.18);
insert into products (id, name, price) values (730, 'Fish - Bones', 77.01);
insert into products (id, name, price) values (731, 'Brandy - Bar', 55.97);
insert into products (id, name, price) values (732, 'Beef - Striploin', 75.4);
insert into products (id, name, price) values (733, 'Salmon - Fillets', 34.93);
insert into products (id, name, price) values (734, 'Wine - Piper Heidsieck Brut', 36.7);
insert into products (id, name, price) values (735, 'Fork - Plastic', 46.39);
insert into products (id, name, price) values (736, 'Seedlings - Mix, Organic', 95.67);
insert into products (id, name, price) values (737, 'Olives - Morracan Dired', 4.19);
insert into products (id, name, price) values (738, 'Tomatoes', 68.16);
insert into products (id, name, price) values (739, 'Arctic Char - Fresh, Whole', 75.13);
insert into products (id, name, price) values (740, 'Lotus Leaves', 24.2);
insert into products (id, name, price) values (741, 'Lettuce - Treviso', 12.61);
insert into products (id, name, price) values (742, 'Cheese - Ermite Bleu', 62.17);
insert into products (id, name, price) values (743, 'Dried Apple', 88.02);
insert into products (id, name, price) values (744, 'Creme De Menth - White', 67.25);
insert into products (id, name, price) values (745, 'Skewers - Bamboo', 70.74);
insert into products (id, name, price) values (746, 'Turkey Tenderloin Frozen', 51.62);
insert into products (id, name, price) values (747, 'Fish - Halibut, Cold Smoked', 68.4);
insert into products (id, name, price) values (748, 'Coffee - Hazelnut Cream', 49.71);
insert into products (id, name, price) values (749, 'Sauce - Apple, Unsweetened', 68.9);
insert into products (id, name, price) values (750, 'Dill Weed - Fresh', 66.61);
insert into products (id, name, price) values (751, 'Appetizer - Shrimp Puff', 95.82);
insert into products (id, name, price) values (752, 'Cake - Night And Day Choclate', 65.37);
insert into products (id, name, price) values (753, 'Cake - Pancake', 55.62);
insert into products (id, name, price) values (754, 'The Pop Shoppe - Grape', 93.26);
insert into products (id, name, price) values (755, 'Yukon Jack', 49.97);
insert into products (id, name, price) values (756, 'Pepper - Red Chili', 60.44);
insert into products (id, name, price) values (757, 'Pepper - Paprika, Hungarian', 61.75);
insert into products (id, name, price) values (758, 'Mini - Vol Au Vents', 49.88);
insert into products (id, name, price) values (759, 'Towels - Paper / Kraft', 60.57);
insert into products (id, name, price) values (760, 'Doilies - 12, Paper', 34.84);
insert into products (id, name, price) values (761, 'Praline Paste', 5.88);
insert into products (id, name, price) values (762, 'Pepper - Jalapeno', 41.05);
insert into products (id, name, price) values (763, 'Coconut - Whole', 82.84);
insert into products (id, name, price) values (764, 'Chocolate Bar - Coffee Crisp', 41.08);
insert into products (id, name, price) values (765, 'Longos - Chicken Caeser Salad', 98.61);
insert into products (id, name, price) values (766, 'Wine - White, Chardonnay', 45.39);
insert into products (id, name, price) values (767, 'Slt - Individual Portions', 58.76);
insert into products (id, name, price) values (768, 'Table Cloth 62x114 Colour', 30.64);
insert into products (id, name, price) values (769, 'Veal - Inside', 73.77);
insert into products (id, name, price) values (770, 'Asparagus - Mexican', 70.7);
insert into products (id, name, price) values (771, 'Soup - Campbells, Spinach Crm', 60.49);
insert into products (id, name, price) values (772, 'Wine - Prosecco Valdobiaddene', 70.22);
insert into products (id, name, price) values (773, 'Pasta - Gnocchi, Potato', 69.97);
insert into products (id, name, price) values (774, 'Dip - Tapenade', 94.84);
insert into products (id, name, price) values (775, 'Yeast Dry - Fleischman', 21.67);
insert into products (id, name, price) values (776, 'Liners - Baking Cups', 14.38);
insert into products (id, name, price) values (777, 'Goldschalger', 7.24);
insert into products (id, name, price) values (778, 'Table Cloth 53x69 White', 49.19);
insert into products (id, name, price) values (779, 'Coconut - Shredded, Unsweet', 54.92);
insert into products (id, name, price) values (780, 'Chick Peas - Dried', 11.51);
insert into products (id, name, price) values (781, 'Egg - Salad Premix', 5.93);
insert into products (id, name, price) values (782, 'Cake Slab', 20.97);
insert into products (id, name, price) values (783, 'Capers - Ox Eye Daisy', 27.05);
insert into products (id, name, price) values (784, 'Pectin', 63.55);
insert into products (id, name, price) values (785, 'Sauce - Gravy, Au Jus, Mix', 12.21);
insert into products (id, name, price) values (786, 'Cheese - Cheddar With Claret', 66.7);
insert into products (id, name, price) values (787, 'Energy Drink Red Bull', 1.58);
insert into products (id, name, price) values (788, 'Relish', 41.6);
insert into products (id, name, price) values (789, 'Veal - Brisket, Provimi, Bone - In', 99.99);
insert into products (id, name, price) values (790, 'Crab Meat Claw Pasteurise', 23.48);
insert into products (id, name, price) values (791, 'Mace Ground', 58.15);
insert into products (id, name, price) values (792, 'Flower - Dish Garden', 78.45);
insert into products (id, name, price) values (793, 'Beer - Steamwhistle', 79.63);
insert into products (id, name, price) values (794, 'Vinegar - Tarragon', 92.36);
insert into products (id, name, price) values (795, 'Chocolate - Pistoles, Lactee, Milk', 72.84);
insert into products (id, name, price) values (796, 'Amaretto', 38.2);
insert into products (id, name, price) values (797, 'Bag - Clear 7 Lb', 68.79);
insert into products (id, name, price) values (798, 'Wine - Alsace Gewurztraminer', 19.25);
insert into products (id, name, price) values (799, 'Bread - Flat Bread', 20.55);
insert into products (id, name, price) values (800, 'Cheese - Pont Couvert', 21.8);
insert into products (id, name, price) values (801, 'Pasta - Shells, Medium, Dry', 48.01);
insert into products (id, name, price) values (802, 'Chicken Breast Halal', 9.59);
insert into products (id, name, price) values (803, 'Wine - Muscadet Sur Lie', 54.57);
insert into products (id, name, price) values (804, 'Doilies - 10, Paper', 42.89);
insert into products (id, name, price) values (805, 'Pumpkin', 2.51);
insert into products (id, name, price) values (806, 'Ice Cream Bar - Drumstick', 29.56);
insert into products (id, name, price) values (807, 'Rice - Sushi', 93.49);
insert into products (id, name, price) values (808, 'Wine - Red, Marechal Foch', 14.86);
insert into products (id, name, price) values (809, 'Oil - Olive Bertolli', 83.52);
insert into products (id, name, price) values (810, 'Truffle Cups - White Paper', 29.11);
insert into products (id, name, price) values (811, 'Nori Sea Weed', 82.07);
insert into products (id, name, price) values (812, 'Canada Dry', 58.48);
insert into products (id, name, price) values (813, 'Beef - Roasted, Cooked', 72.51);
insert into products (id, name, price) values (814, 'Wine - Dubouef Macon - Villages', 92.23);
insert into products (id, name, price) values (815, 'Wine - Shiraz Wolf Blass Premium', 43.94);
insert into products (id, name, price) values (816, 'Cheese - Havarti, Salsa', 10.58);
insert into products (id, name, price) values (817, 'Zucchini - Yellow', 6.75);
insert into products (id, name, price) values (818, 'Macaroons - Homestyle Two Bit', 7.91);
insert into products (id, name, price) values (819, 'Soup - Campbells, Minestrone', 16.91);
insert into products (id, name, price) values (820, 'Five Alive Citrus', 14.64);
insert into products (id, name, price) values (821, 'Yogurt - French Vanilla', 32.45);
insert into products (id, name, price) values (822, 'Wine - Ej Gallo Sonoma', 2.49);
insert into products (id, name, price) values (823, 'Pork - Ham Hocks - Smoked', 80.37);
insert into products (id, name, price) values (824, 'Ice Cream - Life Savers', 87.38);
insert into products (id, name, price) values (825, 'Carbonated Water - Raspberry', 47.9);
insert into products (id, name, price) values (826, 'Cabbage - Nappa', 45.48);
insert into products (id, name, price) values (827, 'Bread - Petit Baguette', 7.9);
insert into products (id, name, price) values (828, 'Mousse - Banana Chocolate', 68.29);
insert into products (id, name, price) values (829, 'Ecolab - Hobart Washarm End Cap', 13.6);
insert into products (id, name, price) values (830, 'Pork - Side Ribs', 33.99);
insert into products (id, name, price) values (831, 'Flower - Daisies', 15.88);
insert into products (id, name, price) values (832, 'Apples - Sliced / Wedge', 67.94);
insert into products (id, name, price) values (833, 'Appetizer - Cheese Bites', 92.01);
insert into products (id, name, price) values (834, 'Evaporated Milk - Skim', 88.93);
insert into products (id, name, price) values (835, 'Assorted Desserts', 87.01);
insert into products (id, name, price) values (836, 'Juice - Pineapple, 341 Ml', 64.12);
insert into products (id, name, price) values (837, 'Chicken - White Meat, No Tender', 61.22);
insert into products (id, name, price) values (838, 'Soupfoamcont12oz 112con', 4.22);
insert into products (id, name, price) values (839, 'Dates', 86.12);
insert into products (id, name, price) values (840, 'Pasta - Penne, Rigate, Dry', 62.3);
insert into products (id, name, price) values (841, 'Scallops 60/80 Iqf', 92.11);
insert into products (id, name, price) values (842, 'Vinegar - Balsamic, White', 19.8);
insert into products (id, name, price) values (843, 'Veal - Insides, Grains', 79.7);
insert into products (id, name, price) values (844, 'Pails With Lids', 92.06);
insert into products (id, name, price) values (845, 'Sprouts - China Rose', 19.67);
insert into products (id, name, price) values (846, 'Pie Filling - Cherry', 73.76);
insert into products (id, name, price) values (847, 'Pineapple - Canned, Rings', 18.96);
insert into products (id, name, price) values (848, 'Celery Root', 85.06);
insert into products (id, name, price) values (849, 'Aspic - Amber', 42.01);
insert into products (id, name, price) values (850, 'Shrimp - 100 / 200 Cold Water', 10.75);
insert into products (id, name, price) values (851, 'Cheese - Cream Cheese', 52.9);
insert into products (id, name, price) values (852, 'Pepper - Scotch Bonnet', 90.06);
insert into products (id, name, price) values (853, 'Sea Bass - Fillets', 50.89);
insert into products (id, name, price) values (854, 'Cabbage - Nappa', 84.67);
insert into products (id, name, price) values (855, 'Ezy Change Mophandle', 99.53);
insert into products (id, name, price) values (856, 'Wine - Cava Aria Estate Brut', 1.49);
insert into products (id, name, price) values (857, 'Rum - White, Gg White', 16.13);
insert into products (id, name, price) values (858, 'Bacardi Breezer - Strawberry', 96.84);
insert into products (id, name, price) values (859, 'Gin - Gilbeys London, Dry', 16.72);
insert into products (id, name, price) values (860, 'Salt - Sea', 52.23);
insert into products (id, name, price) values (861, 'Cheese - Brie', 97.54);
insert into products (id, name, price) values (862, 'Green Scrubbie Pad H.duty', 87.84);
insert into products (id, name, price) values (863, 'Chips - Assorted', 19.98);
insert into products (id, name, price) values (864, 'Wine - Kwv Chenin Blanc South', 57.72);
insert into products (id, name, price) values (865, 'Wine - Stoneliegh Sauvignon', 48.96);
insert into products (id, name, price) values (866, 'Beef - Tenderloin - Aa', 91.47);
insert into products (id, name, price) values (867, 'Latex Rubber Gloves Size 9', 83.7);
insert into products (id, name, price) values (868, 'Pork - Bacon,back Peameal', 90.86);
insert into products (id, name, price) values (869, 'Spring Roll Wrappers', 16.33);
insert into products (id, name, price) values (870, 'Island Oasis - Pina Colada', 72.75);
insert into products (id, name, price) values (871, 'Wine - Crozes Hermitage E.', 50.69);
insert into products (id, name, price) values (872, 'Lemonade - Black Cherry, 591 Ml', 50.65);
insert into products (id, name, price) values (873, 'Wine - Lou Black Shiraz', 19.34);
insert into products (id, name, price) values (874, 'Scotch - Queen Anne', 13.36);
insert into products (id, name, price) values (875, 'Toothpick Frilled', 1.03);
insert into products (id, name, price) values (876, 'Red Currants', 8.5);
insert into products (id, name, price) values (877, 'Barley - Pearl', 51.77);
insert into products (id, name, price) values (878, 'Munchies Honey Sweet Trail Mix', 18.78);
insert into products (id, name, price) values (879, 'Dill - Primerba, Paste', 38.47);
insert into products (id, name, price) values (880, 'Veal - Round, Eye Of', 9.32);
insert into products (id, name, price) values (881, 'Salt - Rock, Course', 94.53);
insert into products (id, name, price) values (882, 'Sprite - 355 Ml', 53.45);
insert into products (id, name, price) values (883, 'Chef Hat 20cm', 77.25);
insert into products (id, name, price) values (884, 'Chicken - Leg, Fresh', 17.63);
insert into products (id, name, price) values (885, 'Bread - Multigrain, Loaf', 46.05);
insert into products (id, name, price) values (886, 'Garbag Bags - Black', 48.42);
insert into products (id, name, price) values (887, 'Wine - Charddonnay Errazuriz', 40.29);
insert into products (id, name, price) values (888, 'Cheese - Boursin, Garlic / Herbs', 34.16);
insert into products (id, name, price) values (889, 'V8 Splash Strawberry Banana', 68.83);
insert into products (id, name, price) values (890, 'Lime Cordial - Roses', 74.11);
insert into products (id, name, price) values (891, 'Calaloo', 91.56);
insert into products (id, name, price) values (892, 'Skirt - 29 Foot', 5.17);
insert into products (id, name, price) values (893, 'Appetiser - Bought', 7.03);
insert into products (id, name, price) values (894, 'Walkers Special Old Whiskey', 75.56);
insert into products (id, name, price) values (895, 'Pastry - Lemon Danish - Mini', 5.89);
insert into products (id, name, price) values (896, 'Capers - Ox Eye Daisy', 9.07);
insert into products (id, name, price) values (897, 'Lentils - Red, Dry', 34.82);
insert into products (id, name, price) values (898, 'Yams', 12.26);
insert into products (id, name, price) values (899, 'Garbage Bags - Black', 64.96);
insert into products (id, name, price) values (900, 'Salt - Celery', 16.15);
insert into products (id, name, price) values (901, 'Apple - Royal Gala', 16.25);
insert into products (id, name, price) values (902, 'Table Cloth - 53x69 Colour', 86.1);
insert into products (id, name, price) values (903, 'Fireball Whisky', 88.87);
insert into products (id, name, price) values (904, 'Cheese - Camembert', 28.12);
insert into products (id, name, price) values (905, 'Pate - Peppercorn', 51.64);
insert into products (id, name, price) values (906, 'Pie Pecan', 8.87);
insert into products (id, name, price) values (907, 'Clams - Canned', 50.27);
insert into products (id, name, price) values (908, 'Parsnip', 96.31);
insert into products (id, name, price) values (909, 'Cafe Royale', 76.63);
insert into products (id, name, price) values (910, 'Bread - Sticks, Thin, Plain', 19.9);
insert into products (id, name, price) values (911, 'Fennel - Seeds', 41.86);
insert into products (id, name, price) values (912, 'General Purpose Trigger', 68.04);
insert into products (id, name, price) values (913, 'Soup - Campbells Pasta Fagioli', 47.12);
insert into products (id, name, price) values (914, 'Coffee Cup 8oz 5338cd', 31.3);
insert into products (id, name, price) values (915, 'Scampi Tail', 95.08);
insert into products (id, name, price) values (916, 'Flour - Bran, Red', 78.82);
insert into products (id, name, price) values (917, 'Water - Spring 1.5lit', 13.32);
insert into products (id, name, price) values (918, 'Bagel - Sesame Seed Presliced', 34.4);
insert into products (id, name, price) values (919, 'True - Vue Containers', 43.69);
insert into products (id, name, price) values (920, 'Bread - Sour Batard', 54.99);
insert into products (id, name, price) values (921, 'Extract - Almond', 90.95);
insert into products (id, name, price) values (922, 'Ice Cream - Vanilla', 87.9);
insert into products (id, name, price) values (923, 'Carbonated Water - Blackberry', 37.05);
insert into products (id, name, price) values (924, 'Seedlings - Mix, Organic', 50.11);
insert into products (id, name, price) values (925, 'Milk - 1%', 9.67);
insert into products (id, name, price) values (926, 'Cocoa Powder - Dutched', 37.44);
insert into products (id, name, price) values (927, 'Green Tea Refresher', 81.51);
insert into products (id, name, price) values (928, 'Salsify, Organic', 46.11);
insert into products (id, name, price) values (929, 'Rosemary - Fresh', 48.8);
insert into products (id, name, price) values (930, 'Wine - Touraine Azay - Le - Rideau', 87.99);
insert into products (id, name, price) values (931, 'Soup - Knorr, Classic Can. Chili', 2.37);
insert into products (id, name, price) values (932, 'Shrimp - Baby, Cold Water', 47.81);
insert into products (id, name, price) values (933, 'Banana', 92.57);
insert into products (id, name, price) values (934, 'Wine - Red, Black Opal Shiraz', 22.57);
insert into products (id, name, price) values (935, 'Wine - Dubouef Macon - Villages', 37.85);
insert into products (id, name, price) values (936, 'Parsley - Fresh', 12.41);
insert into products (id, name, price) values (937, 'Cheese - Mozzarella, Shredded', 41.33);
insert into products (id, name, price) values (938, 'Beans - Long, Chinese', 88.23);
insert into products (id, name, price) values (939, 'Pork - Hock And Feet Attached', 84.3);
insert into products (id, name, price) values (940, 'Bread - Crusty Italian Poly', 50.19);
insert into products (id, name, price) values (941, 'Lotus Leaves', 67.4);
insert into products (id, name, price) values (942, 'Bouillion - Fish', 10.46);
insert into products (id, name, price) values (943, 'Duck - Whole', 28.04);
insert into products (id, name, price) values (944, 'Wiberg Super Cure', 71.28);
insert into products (id, name, price) values (945, 'Nougat - Paste / Cream', 3.41);
insert into products (id, name, price) values (946, 'Juice - Grape, White', 51.68);
insert into products (id, name, price) values (947, 'Soup - Tomato Mush. Florentine', 25.86);
insert into products (id, name, price) values (948, 'Coriander - Ground', 2.99);
insert into products (id, name, price) values (949, 'Wine - Coteaux Du Tricastin Ac', 95.08);
insert into products (id, name, price) values (950, 'Water - Spring 1.5lit', 14.75);
insert into products (id, name, price) values (951, 'Pork - Bones', 56.44);
insert into products (id, name, price) values (952, 'Cake - Cake Sheet Macaroon', 43.01);
insert into products (id, name, price) values (953, 'Vinegar - Cider', 83.77);
insert into products (id, name, price) values (954, 'Cranberries - Dry', 9.48);
insert into products (id, name, price) values (955, 'Extract - Almond', 60.66);
insert into products (id, name, price) values (956, 'Wine - Vineland Estate Semi - Dry', 18.76);
insert into products (id, name, price) values (957, 'Peas - Frozen', 50.8);
insert into products (id, name, price) values (958, 'Broom And Brush Rack Black', 34.68);
insert into products (id, name, price) values (959, 'Bread - Pita, Mini', 34.1);
insert into products (id, name, price) values (960, 'Beer - True North Strong Ale', 70.43);
insert into products (id, name, price) values (961, 'Syrup - Monin, Irish Cream', 7.43);
insert into products (id, name, price) values (962, 'Mushroom - Trumpet, Dry', 11.56);
insert into products (id, name, price) values (963, 'Bacon Strip Precooked', 51.02);
insert into products (id, name, price) values (964, 'Dill Weed - Fresh', 53.91);
insert into products (id, name, price) values (965, 'Vermacelli - Sprinkles, Assorted', 59.23);
insert into products (id, name, price) values (966, 'English Muffin', 32.5);
insert into products (id, name, price) values (967, 'Wine - White, Colubia Cresh', 74.52);
insert into products (id, name, price) values (968, 'Nacho Chips', 17.27);
insert into products (id, name, price) values (969, 'Drambuie', 23.98);
insert into products (id, name, price) values (970, 'Hot Chocolate - Individual', 65.18);
insert into products (id, name, price) values (971, 'Mustard - Dijon', 70.06);
insert into products (id, name, price) values (972, 'Venison - Denver Leg Boneless', 70.22);
insert into products (id, name, price) values (973, 'Quail - Jumbo', 85.95);
insert into products (id, name, price) values (974, 'Iced Tea - Lemon, 460 Ml', 66.23);
insert into products (id, name, price) values (975, 'Yogurt - Plain', 72.53);
insert into products (id, name, price) values (976, 'Rye Special Old', 3.95);
insert into products (id, name, price) values (977, 'Lid - 0090 Clear', 72.59);
insert into products (id, name, price) values (978, 'Cheese - Victor Et Berthold', 43.84);
insert into products (id, name, price) values (979, 'Peas - Pigeon, Dry', 13.92);
insert into products (id, name, price) values (980, 'Shichimi Togarashi Peppeers', 56.24);
insert into products (id, name, price) values (981, 'Oysters - Smoked', 29.59);
insert into products (id, name, price) values (982, 'Shrimp - Black Tiger 13/15', 82.03);
insert into products (id, name, price) values (983, 'Wine - Red, Cabernet Sauvignon', 6.75);
insert into products (id, name, price) values (984, 'Port - 74 Brights', 68.59);
insert into products (id, name, price) values (985, 'Port - 74 Brights', 18.98);
insert into products (id, name, price) values (986, 'Lettuce - Escarole', 87.4);
insert into products (id, name, price) values (987, 'Muffin Mix - Lemon Cranberry', 86.21);
insert into products (id, name, price) values (988, 'Bread - Italian Roll With Herbs', 79.38);
insert into products (id, name, price) values (989, 'Grapes - Green', 4.34);
insert into products (id, name, price) values (990, 'Pan Grease', 35.87);
insert into products (id, name, price) values (991, 'Shrimp - Baby, Warm Water', 4.4);
insert into products (id, name, price) values (992, 'Tea - English Breakfast', 44.73);
insert into products (id, name, price) values (993, 'Beans - Long, Chinese', 21.48);
insert into products (id, name, price) values (994, 'Flower - Daisies', 78.85);
insert into products (id, name, price) values (995, 'Flavouring - Rum', 40.3);
insert into products (id, name, price) values (996, 'Wiberg Super Cure', 9.84);
insert into products (id, name, price) values (997, 'Cabbage - Green', 29.95);
insert into products (id, name, price) values (998, 'Lamb Leg - Bone - In Nz', 89.74);
insert into products (id, name, price) values (999, 'Bouillion - Fish', 75.39);
insert into products (id, name, price) values (1000, 'Oysters - Smoked', 39.0);
